// Package shell provides the shell-integration layer for gwt.
//
// # The cd protocol
//
// A process cannot change its parent shell's working directory. The switch
// verbs (new, from, co/checkout, search/pick) and the bare dashboard invocation
// therefore print ONLY the chosen worktree path to stdout; all diagnostics,
// prompts, and the TUI render to stderr / the tty. A small shell wrapper
// function captures that stdout and cd's the interactive shell into it.
//
// Optionally, gwt may emit a single line prefixed with "GWT_POPULATE:" instead
// of a bare path. This is used by from/co invoked with no argument: rather than
// cd-ing somewhere, the wrapper writes the remainder of the line (a suggested
// command) into the shell's line editor so the user can review and edit it
// before pressing Enter. zsh uses `print -z`; bash uses the readline buffer
// (falling back to history + a printed line); fish uses `commandline`.
//
// # Wiring from cmd/shell.go
//
// The integration agent's cmd/shell.go should implement `gwt shell-init <shell>`
// roughly as:
//
//	script, err := shell.Init(args[0])
//	if err != nil {
//	    return err // unsupported shell; mention shell.Shells() for valid values
//	}
//	fmt.Fprintln(cmd.OutOrStdout(), script)
//
// The user then evals it from their rc, e.g. `eval "$(gwt shell-init zsh)"` for
// zsh/bash, or `gwt shell-init fish | source` for fish.
//
// Completion scripts are generated by cobra itself via `gwt completion <shell>`
// and are not authored here; see CompletionNote for the wiring hint.
package shell

import (
	_ "embed"
	"fmt"
)

//go:embed wrapper_zsh.sh
var wrapperZsh string

//go:embed wrapper_bash.sh
var wrapperBash string

//go:embed wrapper_fish.fish
var wrapperFish string

// CompletionNote is a hint for the integration agent: completion scripts are
// produced by cobra's generated `completion` command, not by this package.
const CompletionNote = "completions are generated by cobra: `gwt completion <shell>`"

// Init returns the shell wrapper script for the given shell. Supported shells
// are "zsh", "bash", and "fish" (see Shells). It returns an error for any other
// value. The returned script is safe to evaluate, e.g. `eval "$(gwt shell-init
// zsh)"` or `gwt shell-init fish | source`.
func Init(shell string) (string, error) {
	switch shell {
	case "zsh":
		return wrapperZsh, nil
	case "bash":
		return wrapperBash, nil
	case "fish":
		return wrapperFish, nil
	default:
		return "", fmt.Errorf("unsupported shell %q: supported shells are %v", shell, Shells())
	}
}

// Shells lists the shells for which Init can produce a wrapper script.
func Shells() []string {
	return []string{"zsh", "bash", "fish"}
}
