// Package shell provides the shell-integration layer for gwt.
//
// # The cd protocol
//
// A process cannot change its parent shell's working directory. The switch
// verbs (new, from, co/checkout, search/pick) and the bare dashboard invocation
// therefore print ONLY the chosen worktree path to stdout (or GWT_PATH_OUT when
// the shell wrapper sets it); all diagnostics, prompts, and the TUI render to
// stderr / the tty. A small shell wrapper function reads the path and cd's the
// interactive shell into it. The wrapper uses GWT_PATH_OUT instead of command
// substitution so long-running setup (uv sync, pnpm install) can stream progress.
//
// Optionally, gwt may emit a single line prefixed with "GWT_POPULATE:" instead
// of a bare path. This is used by from/co invoked with no argument: rather than
// cd-ing somewhere, the wrapper writes the remainder of the line (a suggested
// command) into the shell's line editor so the user can review and edit it
// before pressing Enter. zsh uses `print -z`; bash uses the readline buffer
// (falling back to history + a printed line); fish uses `commandline`.
//
// # Wiring from cmd/shell.go
//
// The integration agent's cmd/shell.go should implement `gwt shell-init <shell>`
// roughly as:
//
//	bin, _ := os.Executable()
//	script, err := shell.Init(args[0], name, bin)
//	if err != nil {
//	    return err // unsupported shell; mention shell.Shells() for valid values
//	}
//	fmt.Fprintln(cmd.OutOrStdout(), script)
//
// The user then evals it from their rc, e.g. `eval "$(gwt shell-init zsh)"` for
// zsh/bash, or `gwt shell-init fish | source` for fish. Re-run shell-init after
// installing a new binary so _GWT_BIN points at the build you intend to run.
//
// Completion scripts are generated by cobra itself via `gwt completion <shell>`
// and are not authored here; see CompletionNote for the wiring hint.
package shell

import (
	_ "embed"
	"fmt"
	"strings"
)

//go:embed wrapper_zsh.sh
var wrapperZsh string

//go:embed wrapper_bash.sh
var wrapperBash string

//go:embed wrapper_fish.fish
var wrapperFish string

// CompletionNote is a hint for the integration agent: completion scripts are
// produced by cobra's generated `completion` command, not by this package.
const CompletionNote = "completions are generated by cobra: `gwt completion <shell>`"

// Init returns the shell wrapper script for the given shell. Supported shells
// are "zsh", "bash", and "fish" (see Shells). binPath is the absolute path to
// the gwt binary the wrapper must invoke; shell-init sets this from the binary
// that generated the script so PATH ordering cannot silently run a stale copy.
//
// name is the command/function name the wrapper defines. Pass "gwt" for the
// default; pass e.g. "oldgwt" when installed under a different name. The
// returned script is safe to evaluate, e.g.
// `eval "$(/path/to/gwt shell-init zsh --name oldgwt)"`.
func Init(shell, name, binPath string) (string, error) {
	var base string
	switch shell {
	case "zsh":
		base = wrapperZsh
	case "bash":
		base = wrapperBash
	case "fish":
		base = wrapperFish
	default:
		return "", fmt.Errorf("unsupported shell %q: supported shells are %v", shell, Shells())
	}
	if name == "" {
		name = "gwt"
	}
	if name != "gwt" {
		// Every lowercase "gwt" in the wrappers is the command/function name
		// (the GWT_POPULATE sentinel is uppercase and untouched).
		base = strings.ReplaceAll(base, "gwt", name)
	}
	q := shellQuote(binPath)
	header := binVarHeader(shell, q)
	return header + base + "\n" + completionSnippet(shell), nil
}

func binVarHeader(shell, quotedPath string) string {
	switch shell {
	case "fish":
		return fmt.Sprintf("set -g GWT_BIN %s\n", quotedPath)
	default:
		return fmt.Sprintf("_GWT_BIN=%s\n", quotedPath)
	}
}

func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", "'\\''") + "'"
}

func completionSnippet(shell string) string {
	switch shell {
	case "zsh":
		return `# Tab-complete gwt subcommands, flags, and worktree/branch names.
if builtin command -v compdef >/dev/null 2>&1; then
  eval "$("$_GWT_BIN" completion zsh)"
fi`
	case "bash":
		return `# Tab-complete gwt subcommands, flags, and worktree/branch names.
if [[ -n ${BASH_VERSION:-} ]]; then
  eval "$("$_GWT_BIN" completion bash)"
fi`
	case "fish":
		return `# Tab-complete gwt subcommands, flags, and worktree/branch names.
$GWT_BIN completion fish | source`
	default:
		return ""
	}
}

// Shells lists the shells for which Init can produce a wrapper script.
func Shells() []string {
	return []string{"zsh", "bash", "fish"}
}
